version: '3.9'
services:
  oracle:
    image: local/oraclesqlplus:${TAG:-latest}
    container_name: oraclesqlplus
    build: .
    restart: always
    # platform: linux/arm64
    entrypoint: sqlplus
